import {test,expect} from '@playwright/test';
test('real imported catalogue has bounded search and rejects malformed limits',async({request})=>{
  const summary=await request.get('/api/locations?mode=summary');expect(summary.status()).toBe(200);
  expect(await summary.json()).toMatchObject({total:763953,campaign:55731,global:708222,executionReady:0});
  for(const limit of ['abc','NaN','Infinity','0','501']) expect((await request.get(`/api/locations?limit=${limit}`)).status()).toBe(400);
  expect((await request.get('/api/tlps/snapshots/data.db')).status()).toBe(404);
  const result=await request.get('/api/locations?corpus=global&q=Paris&limit=2');const body=await result.json();
  expect(body.records).toHaveLength(2);expect(body.hasMore).toBe(true);
  expect(body.records[0].sourceRecord.verification_status).toBe('GEONAMES_COORDINATE_UNVERIFIED');
});
test('native map, search, evidence, export and mobile layout use real data',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/locations');
  await expect(page.getByText('708,222',{exact:true})).toBeVisible();
  await page.getByLabel('Collection',{exact:true}).selectOption('global');
  await page.getByLabel('Search names and places').fill('Paris');
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await expect(page.getByRole('status').first()).toContainText('matches');
  await expect(page.locator('[data-testid="location-map"] .leaflet-interactive').first()).toBeVisible();
  await page.getByRole('region',{name:'Location results'}).getByRole('button').first().click();
  await expect(page.getByRole('region',{name:'Source evidence'})).toContainText('GEONAMES_COORDINATE_UNVERIFIED');
  await expect(page.getByRole('link',{name:'Open original source'})).toHaveAttribute('href',/https:\/\/www.geonames.org\//);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export this page (JSON)'}).click();expect((await download).suggestedFilename()).toBe('brahmini-locations-page.json');
  await page.getByRole('button',{name:'Fit results',exact:true}).click();
  await page.getByRole('button',{name:'Search this map area'}).click();
  await expect(page.getByRole('button',{name:'Clear map boundary'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
test('campaign explorer loads every absorbed dataset and its map controls',async({page})=>{
  await page.goto('/locations/campaign');
  const explorer=page.frameLocator('iframe[title="TLPS campaign map and registry"]');
  await expect(explorer.locator('#mRecords')).toHaveText('55731',{timeout:30000});
  await explorer.locator('[data-view="mapview"]').click();
  await expect(explorer.locator('#map.leaflet-container')).toBeVisible();
  await expect(explorer.locator('#radarBtn')).toBeVisible();
  await explorer.locator('#radarBtn').click();
  await expect(explorer.locator('#radarStatus')).not.toHaveText('Radar disabled');
  await explorer.getByRole('button',{name:'+ New pin',exact:true}).click();
  await explorer.locator('#eName').fill('Browser persistence check');
  await explorer.locator('#saveRecordBtn').click();
  await expect(explorer.locator('#mRecords')).toHaveText('55732');
  const stored=await page.evaluate(()=>localStorage.getItem('brahmini-tlps-campaign-v1'));
  expect(JSON.parse(stored!).records).toHaveLength(1);
  expect(stored!.length).toBeLessThan(10000);
  await page.reload();
  await expect(explorer.locator('#mRecords')).toHaveText('55732',{timeout:30000});
  await explorer.locator('[data-view="registry"]').click();
  await explorer.locator('#q').fill('Browser persistence check');
  await expect(explorer.locator('#registryBody')).toContainText('Browser persistence check');
});
