'use client';
import Script from 'next/script';
import {useEffect,useRef,useState} from 'react';
type Pin={id:string;name:string;category:string;latitude:number|null;longitude:number|null;maps_url:string};
type Live={matchedPlanners:number;runnerState:string;counts:{status:string;count:number}[];totalDistricts:number};
export default function FloatingPlannerMap({state,live}:{state:string;live:Live|null}){
 const [open,setOpen]=useState(true),[ready,setReady]=useState(false),[pins,setPins]=useState<Pin[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[selected,setSelected]=useState<Pin|null>(null),[updated,setUpdated]=useState('');
 const host=useRef<HTMLDivElement>(null),map=useRef<any>(null),layer=useRef<any>(null),fitNext=useRef(true);
 useEffect(()=>{let active=true;fitNext.current=true;setPins([]);setSelected(null);setUpdated('');setTotal(0);async function poll(){try{const r=await fetch('/api/event-planners?'+new URLSearchParams({state,limit:'200'}),{cache:'no-store'});if(!r.ok)throw Error('Map data unavailable');const b=await r.json();if(active){setPins(b.records.filter((p:Pin)=>p.latitude!=null&&p.longitude!=null));setTotal(b.total);setUpdated(new Date().toLocaleTimeString());setError('');}}catch{if(active)setError('Update failed; displayed pins may be stale.');}}void poll();const timer=setInterval(poll,10000);return()=>{active=false;clearInterval(timer);};},[state]);
 useEffect(()=>{if(!open||!ready||!host.current||!window.L)return;const L=window.L;map.current=L.map(host.current).setView([22.5,79],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>setError('Basemap unavailable; collected pins remain visible.')).addTo(map.current);layer.current=L.layerGroup().addTo(map.current);fitNext.current=true;const observer=new ResizeObserver(()=>map.current?.invalidateSize());observer.observe(host.current);return()=>{observer.disconnect();map.current?.remove();map.current=null;layer.current=null;};},[ready,open]);
 function fit(){if(pins.length&&map.current)map.current.fitBounds(pins.map(p=>[p.latitude,p.longitude]),{padding:[24,24],maxZoom:11});}
 useEffect(()=>{if(!layer.current||!window.L)return;layer.current.clearLayers();pins.forEach(p=>{const label=document.createElement('span');label.textContent=p.name;window.L.circleMarker([p.latitude,p.longitude],{radius:5,color:'#2dd4bf',fillOpacity:.8}).bindTooltip(label).on('click',()=>setSelected(p)).addTo(layer.current);});if(fitNext.current&&pins.length){fit();fitNext.current=false;}},[pins,ready,open]);
 const succeeded=live?.counts.filter(c=>['limited_view','visible_list_exhausted','no_results'].includes(c.status)).reduce((n,c)=>n+c.count,0);
 return <aside aria-label="Floating live planner map" className="fixed bottom-4 right-4 z-[1000] w-[min(420px,calc(100vw-32px))] overflow-hidden rounded-xl border border-teal-700 bg-slate-950 text-slate-100 shadow-2xl"><link rel="stylesheet" href="/vendor/leaflet/leaflet.css"/><Script src="/vendor/leaflet/leaflet.js" onReady={()=>setReady(true)} onError={()=>setError('Map library unavailable')}/><div className="flex items-center justify-between bg-slate-800 px-4 py-3"><h2 className="font-semibold">Live planner map</h2><button className="rounded bg-slate-700 px-3 py-1 text-sm" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Minimize':'Expand'}</button></div><div className="flex justify-between gap-2 px-4 py-2 text-xs text-teal-200"><span>{live?.matchedPlanners?.toLocaleString()??'—'} planners</span><span>{succeeded??'—'}/{live?.totalDistricts??'—'} succeeded</span><span>{live?.runnerState||'Loading'}</span></div>{open&&<><div className="flex items-center justify-between px-4 py-2 text-xs"><span>{state||'All search states'}</span><button className="rounded bg-teal-800 px-2 py-1" onClick={fit}>Fit pins</button></div><div ref={host} data-testid="planner-live-map" className="h-[260px] bg-slate-800"/>{selected&&<p className="px-4 pt-2 text-sm">{selected.name} · {selected.category}{selected.maps_url.startsWith('https://www.google.com/')&&<> · <a href={selected.maps_url} target="_blank" rel="noreferrer" className="text-teal-300">Maps ↗</a></>}</p>}<p className="px-4 py-3 text-xs text-slate-400">{pins.length} located pins from the first 200 of {total.toLocaleString()} matching planners. Follows the selected test district’s state, or the table state filter. Search associations are unverified.{updated&&` Updated ${updated}; refreshes every 10s.`}</p>{error&&<p role="status" className="px-4 pb-3 text-xs text-amber-300">{error}</p>}</>}</aside>;
}
