'use strict';

const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');

const OUTPUT_LIMIT=512*1024;
function error(message,statusCode=400){return Object.assign(new Error(message),{statusCode});}
function hash(value){return crypto.createHash('sha256').update(value).digest('hex');}
function run(cwd,args){try{return execFileSync('git',args,{cwd,encoding:'utf8',timeout:15000,maxBuffer:OUTPUT_LIMIT,stdio:['ignore','pipe','pipe']});}catch(e){throw error(String(e.stderr||e.message).trim().slice(0,2000),409);}}
function repository(store,scanner,rootId){const root=scanner.approvedRoot(store,rootId);let top;try{top=fs.realpathSync.native(run(root.path,['rev-parse','--show-toplevel']).trim());}catch(_){throw error('The approved root is not a Git repository.',409);}if(top!==root.path)throw error('Approve the exact Git repository root.',409);return root;}
function statusRows(cwd){const raw=run(cwd,['status','--porcelain=v1','-z']);const parts=raw.split('\0').filter(Boolean),rows=[];for(let i=0;i<parts.length;i++){const item=parts[i],code=item.slice(0,2),file=item.slice(3);const renamed=/[RC]/.test(code)&&parts[i+1]?parts[++i]:null;rows.push({code,path:renamed||file,fromPath:renamed?file:null,staged:code[0]!==' '&&code[0]!=='?',working:code[1]!==' '||code==='??'});}return rows;}
function snapshot(store,scanner,rootId){const root=repository(store,scanner,rootId),status=statusRows(root.path);const branches=run(root.path,['branch','--format=%(refname:short)%09%(HEAD)%09%(objectname:short)']).trim().split('\n').filter(Boolean).map(line=>{const [name,head,sha]=line.split('\t');return{name,current:head==='*',sha};});const workingDiff=run(root.path,['diff','--no-ext-diff','--']);const stagedDiff=run(root.path,['diff','--cached','--no-ext-diff','--']);const tests=store.all('workspaceRuns').filter(item=>item.rootId===root.id&&item.action==='test').reverse().slice(0,10).map(item=>({id:item.id,status:item.status,startedAt:item.startedAt,finishedAt:item.finishedAt,command:item.command,outputTruncated:item.truncated}));return{rootId:root.id,repositoryPath:root.path,branch:run(root.path,['branch','--show-current']).trim()||null,head:run(root.path,['rev-parse','--short','HEAD']).trim(),status,branches,workingDiff,stagedDiff,testEvidence:tests,sampledAt:new Date().toISOString(),limits:{diffBytes:OUTPUT_LIMIT}};}
function changedPaths(cwd){return new Set(statusRows(cwd).map(row=>row.path));}
function stagedState(cwd){const files=run(cwd,['diff','--cached','--name-only','--']).trim().split('\n').filter(Boolean);const diff=run(cwd,['diff','--cached','--no-ext-diff','--']);return{files,diff,diffSha256:hash(diff)};}
function createDraft(store,scanner,input){const root=repository(store,scanner,input.rootId),files=[...new Set((input.files||[]).map(String))];if(!files.length)throw error('Select at least one changed file.');const changed=changedPaths(root.path);for(const file of files){if(path.isAbsolute(file)||file.includes('\0')||file.split(/[\\/]/).includes('..')||!changed.has(file))throw error('Only exact changed paths from this repository can be staged: '+file,403);}run(root.path,['add','--',...files]);const staged=stagedState(root.path);if(!staged.files.length)throw error('No staged changes remain after staging.',409);const now=new Date().toISOString(),draft={id:'gitdraft_'+hash(root.id+'|'+now).slice(0,16),type:'git-commit-draft',rootId:root.id,repositoryPath:root.path,status:'awaiting-review',message:String(input.message||'').trim().slice(0,200),requestedFiles:files,stagedFiles:staged.files,stagedDiff:staged.diff,stagedDiffSha256:staged.diffSha256,createdAt:now,updatedAt:now,review:null,commit:null,testEvidence:store.all('workspaceRuns').filter(x=>x.rootId===root.id&&x.action==='test').reverse().slice(0,10).map(x=>({id:x.id,status:x.status,finishedAt:x.finishedAt}))};store.put('workspaceGitDrafts',draft);return draft;}
function reviewDraft(store,scanner,id){const draft=store.get('workspaceGitDrafts',id);if(!draft)throw error('Unknown commit draft.',404);const root=repository(store,scanner,draft.rootId),current=stagedState(root.path);if(current.diffSha256!==draft.stagedDiffSha256||JSON.stringify(current.files)!==JSON.stringify(draft.stagedFiles))throw error('The staged files or diff changed. Create a new draft and review it again.',409);const now=new Date().toISOString();draft.status='reviewed';draft.updatedAt=now;draft.review={reviewedAt:now,exactFiles:[...draft.stagedFiles],stagedDiffSha256:draft.stagedDiffSha256};store.put('workspaceGitDrafts',draft);return draft;}
function commitDraft(store,scanner,id){const draft=store.get('workspaceGitDrafts',id);if(!draft)throw error('Unknown commit draft.',404);if(draft.status!=='reviewed'||!draft.review)throw error('Review the exact staged files and diff before committing.',409);if(!draft.message)throw error('A commit message is required.',409);const root=repository(store,scanner,draft.rootId),current=stagedState(root.path);if(current.diffSha256!==draft.review.stagedDiffSha256||JSON.stringify(current.files)!==JSON.stringify(draft.review.exactFiles))throw error('The staged snapshot changed after review. Commit was stopped.',409);run(root.path,['commit','-m',draft.message]);const now=new Date().toISOString();draft.status='committed';draft.updatedAt=now;draft.commit={sha:run(root.path,['rev-parse','HEAD']).trim(),shortSha:run(root.path,['rev-parse','--short','HEAD']).trim(),committedAt:now,files:[...draft.review.exactFiles],reviewedDiffSha256:draft.review.stagedDiffSha256};store.put('workspaceGitDrafts',draft);return draft;}

module.exports={snapshot,createDraft,reviewDraft,commitDraft,stagedState,constants:{OUTPUT_LIMIT}};
