'use strict';

const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');

const OUTPUT_LIMIT=512*1024;
function error(message,statusCode=400){return Object.assign(new Error(message),{statusCode});}
function hash(value){return crypto.createHash('sha256').update(value).digest('hex');}
function run(cwd,args){try{return execFileSync('git',args,{cwd,encoding:'utf8',timeout:15000,maxBuffer:OUTPUT_LIMIT,stdio:['ignore','pipe','pipe']});}catch(e){throw error(String(e.stderr||e.message).trim().slice(0,2000),409);}}
function repository(store,scanner,rootId){const root=scanner.approvedRoot(store,rootId);let top;try{top=fs.realpathSync.native(run(root.path,['rev-parse','--show-toplevel']).trim());}catch(_){throw error('The approved root is not a Git repository.',409);}if(top!==root.path)throw error('Approve the exact Git repository root.',409);return root;}
function statusRows(cwd){const raw=run(cwd,['status','--porcelain=v1','-z']);const parts=raw.split('\0').filter(Boolean),rows=[];for(let i=0;i<parts.length;i++){const item=parts[i],code=item.slice(0,2),file=item.slice(3);const renamed=/[RC]/.test(code)&&parts[i+1]?parts[++i]:null;rows.push({code,path:renamed||file,fromPath:renamed?file:null,staged:code[0]!==' '&&code[0]!=='?',working:code[1]!==' '||code==='??'});}return rows;}
function snapshot(store,scanner,rootId){const root=repository(store,scanner,rootId),status=statusRows(root.path);const branches=run(root.path,['branch','--format=%(refname:short)%09%(HEAD)%09%(objectname:short)']).trim().split('\n').filter(Boolean).map(line=>{const [name,head,sha]=line.split('\t');return{name,current:head==='*',sha};});const workingDiff=run(root.path,['diff','--no-ext-diff','--']);const stagedDiff=run(root.path,['diff','--cached','--no-ext-diff','--']);const tests=store.all('workspaceRuns').filter(item=>item.rootId===root.id&&item.action==='test').reverse().slice(0,10).map(item=>({id:item.id,status:item.status,startedAt:item.startedAt,finishedAt:item.finishedAt,command:item.command,outputTruncated:item.truncated}));return{rootId:root.id,repositoryPath:root.path,branch:run(root.path,['branch','--show-current']).trim()||null,head:run(root.path,['rev-parse','--short','HEAD']).trim(),status,branches,workingDiff,stagedDiff,testEvidence:tests,sampledAt:new Date().toISOString(),limits:{diffBytes:OUTPUT_LIMIT}};}
function changedPaths(cwd){return new Set(statusRows(cwd).map(row=>row.path));}
function stagedState(cwd){const files=run(cwd,['diff','--cached','--name-only','--']).trim().split('\n').filter(Boolean);const diff=run(cwd,['diff','--cached','--no-ext-diff','--']);return{files,diff,diffSha256:hash(diff)};}
function createDraft(store,scanner,input){const root=repository(store,scanner,input.rootId),files=[...new Set((input.files||[]).map(String))];if(!files.length)throw error('Select at least one changed file.');const changed=changedPaths(root.path);for(const file of files){if(path.isAbsolute(file)||file.includes('\0')||file.split(/[\\/]/).includes('..')||!changed.has(file))throw error('Only exact changed paths from this repository can be staged: '+file,403);}run(root.path,['add','--',...files]);const staged=stagedState(root.path);if(!staged.files.length)throw error('No staged changes remain after staging.',409);const now=new Date().toISOString(),draft={id:'gitdraft_'+hash(root.id+'|'+now).slice(0,16),type:'git-commit-draft',rootId:root.id,repositoryPath:root.path,status:'awaiting-review',message:String(input.message||'').trim().slice(0,200),requestedFiles:files,stagedFiles:staged.files,stagedDiff:staged.diff,stagedDiffSha256:staged.diffSha256,createdAt:now,updatedAt:now,review:null,commit:null,testEvidence:store.all('workspaceRuns').filter(x=>x.rootId===root.id&&x.action==='test').reverse().slice(0,10).map(x=>({id:x.id,status:x.status,finishedAt:x.finishedAt}))};store.put('workspaceGitDrafts',draft);return draft;}
function reviewDraft(store,scanner,id){const draft=store.get('workspaceGitDrafts',id);if(!draft)throw error('Unknown commit draft.',404);const root=repository(store,scanner,draft.rootId),current=stagedState(root.path);if(current.diffSha256!==draft.stagedDiffSha256||JSON.stringify(current.files)!==JSON.stringify(draft.stagedFiles))throw error('The staged files or diff changed. Create a new draft and review it again.',409);const now=new Date().toISOString();draft.status='reviewed';draft.updatedAt=now;draft.review={reviewedAt:now,exactFiles:[...draft.stagedFiles],stagedDiffSha256:draft.stagedDiffSha256};store.put('workspaceGitDrafts',draft);return draft;}
function commitDraft(store,scanner,id){const draft=store.get('workspaceGitDrafts',id);if(!draft)throw error('Unknown commit draft.',404);if(draft.status!=='reviewed'||!draft.review)throw error('Review the exact staged files and diff before committing.',409);if(!draft.message)throw error('A commit message is required.',409);const root=repository(store,scanner,draft.rootId),current=stagedState(root.path);if(current.diffSha256!==draft.review.stagedDiffSha256||JSON.stringify(current.files)!==JSON.stringify(draft.review.exactFiles))throw error('The staged snapshot changed after review. Commit was stopped.',409);run(root.path,['commit','-m',draft.message]);const now=new Date().toISOString();draft.status='committed';draft.updatedAt=now;draft.commit={sha:run(root.path,['rev-parse','HEAD']).trim(),shortSha:run(root.path,['rev-parse','--short','HEAD']).trim(),committedAt:now,files:[...draft.review.exactFiles],reviewedDiffSha256:draft.review.stagedDiffSha256};store.put('workspaceGitDrafts',draft);return draft;}

function history(store,scanner,rootId,limit=30){const root=repository(store,scanner,rootId),count=Math.max(1,Math.min(100,Number(limit)||30));const raw=run(root.path,['log',`-${count}`,'--date=iso-strict','--pretty=format:%H%x09%h%x09%ad%x09%an%x09%s']);return raw.split('\n').filter(Boolean).map(line=>{const [sha,shortSha,committedAt,author,...subject]=line.split('\t');return{sha,shortSha,committedAt,author,subject:subject.join('\t')};});}
function validBranch(name){return typeof name==='string'&&/^(?![-/.])(?!.*(?:\.\.|\/\.|\.$|\.lock$))[A-Za-z0-9._/-]{1,120}$/.test(name)&&!name.endsWith('/');}
function branch(store,scanner,input){const root=repository(store,scanner,input.rootId),name=String(input.name||'').trim();if(!validBranch(name))throw error('Use a valid branch name.');if(statusRows(root.path).length)throw error('Branch operations require a clean working tree.',409);const exists=run(root.path,['branch','--list',name]).trim();if(input.create){if(exists)throw error('Branch already exists.',409);run(root.path,['switch','-c',name]);}else{if(!exists)throw error('Branch does not exist.',404);run(root.path,['switch',name]);}return snapshot(store,scanner,root.id);}
function conflicts(store,scanner,rootId){const root=repository(store,scanner,rootId);return statusRows(root.path).filter(row=>['DD','AU','UD','UA','DU','AA','UU'].includes(row.code)).map(row=>({path:row.path,code:row.code}));}
function preparePullRequest(store,scanner,input){const root=repository(store,scanner,input.rootId),base=String(input.base||'main').trim(),head=run(root.path,['branch','--show-current']).trim();if(!head)throw error('A named current branch is required.',409);if(!validBranch(base))throw error('Use a valid base branch.');run(root.path,['rev-parse','--verify',base]);const commits=run(root.path,['log','--oneline',`${base}..${head}`]).trim();const diffStat=run(root.path,['diff','--stat',`${base}...${head}`]).trim();const now=new Date().toISOString(),action={id:'gitaction_'+hash(root.id+'|pr|'+now).slice(0,16),type:'pull-request-draft',rootId:root.id,status:'draft',base,head,title:String(input.title||`Merge ${head} into ${base}`).trim().slice(0,200),body:String(input.body||'').trim().slice(0,10000),commits,diffStat,createdAt:now};store.put('workspaceGitActions',action);return action;}
function preparePush(store,scanner,input){const root=repository(store,scanner,input.rootId),branchName=run(root.path,['branch','--show-current']).trim(),remote=String(input.remote||'origin').trim();if(!branchName)throw error('A named branch is required.',409);if(!/^[A-Za-z0-9._-]{1,80}$/.test(remote))throw error('Use a valid remote name.');run(root.path,['remote','get-url',remote]);const now=new Date().toISOString(),action={id:'gitaction_'+hash(root.id+'|push|'+now).slice(0,16),type:'push-request',rootId:root.id,status:'awaiting-review',remote,branch:branchName,headSha:run(root.path,['rev-parse','HEAD']).trim(),createdAt:now,review:null};store.put('workspaceGitActions',action);return action;}
function reviewPush(store,scanner,id){const action=store.get('workspaceGitActions',id);if(!action||action.type!=='push-request')throw error('Unknown push request.',404);const root=repository(store,scanner,action.rootId),head=run(root.path,['rev-parse','HEAD']).trim();if(head!==action.headSha)throw error('HEAD changed after push preparation.',409);action.status='reviewed';action.review={reviewedAt:new Date().toISOString(),remote:action.remote,branch:action.branch,headSha:head};store.put('workspaceGitActions',action);return action;}
function executePush(store,scanner,id){const action=store.get('workspaceGitActions',id);if(!action||action.type!=='push-request')throw error('Unknown push request.',404);if(action.status!=='reviewed'||!action.review)throw error('Review the exact remote, branch, and commit before pushing.',409);const root=repository(store,scanner,action.rootId),head=run(root.path,['rev-parse','HEAD']).trim(),branchName=run(root.path,['branch','--show-current']).trim();if(head!==action.review.headSha||branchName!==action.review.branch)throw error('The reviewed push state changed.',409);run(root.path,['push','--set-upstream',action.review.remote,action.review.branch]);action.status='pushed';action.pushedAt=new Date().toISOString();store.put('workspaceGitActions',action);return action;}

module.exports={snapshot,createDraft,reviewDraft,commitDraft,history,branch,conflicts,preparePullRequest,preparePush,reviewPush,executePush,stagedState,constants:{OUTPUT_LIMIT}};
