'use client';
import {useEffect,useState} from 'react';

type Section<T>={available:boolean;data:T|null};
type Collection={total:number;completed:number;pending:number;active:number;businesses:number;percent:number;runnerState:string;pauseReason:string|null;lastProgressAt:string|null};
type Workspace={conversations:number;published:number;drafts:number;recentConversations:{id:string;title:string;category:string;updated_at:string}[];recentPublications:{id:string;title:string;kind:string;category:string;status:string;published_at:string|null;created_at:string}[]};
type Helpers={total:number;scheduled:number;schedulerAvailable:boolean;heartbeat:string|null;waiting:number;working:number;ready:number;needsAttention:number;recentRuns:{id:string;name:string;status:string;conversation_id:string|null;created_at:string;error:string|null}[]};
type Milestone={id:string;title:string;status:'complete'|'in_progress'|'planned';commit:string|null;date:string|null;href:string|null; evidence:string|null};
type Roadmap={generatedAt:string;collection:Section<Collection>;workspace:Section<Workspace>;helpers:Section<Helpers>;milestones:Milestone[]};

const statusLabel={complete:'Complete',in_progress:'In progress',planned:'Planned'};
const runLabel:{[key:string]:string}={queued:'Waiting',running:'Working',complete:'Ready to review',failed:'Needs attention',cancelled:'Cancelled'};
const card='rounded-2xl border border-slate-700 bg-slate-900 p-5';
const date=(value:string|null)=>value?new Date(value).toLocaleString():'Not recorded';

export default function RoadmapPage(){
 const [data,setData]=useState<Roadmap|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;async function refresh(){try{const response=await fetch('/api/roadmap',{cache:'no-store'});const value=await response.json();if(!response.ok)throw Error(value.error||'Roadmap unavailable');if(active){setData(value);setError('')}}catch(e){if(active)setError(e instanceof Error?e.message:'Roadmap unavailable')}}void refresh();const timer=setInterval(refresh,10000);return()=>{active=false;clearInterval(timer)}},[]);
 const collection=data?.collection.data,workspace=data?.workspace.data,helpers=data?.helpers.data;
 return <main className="min-h-screen bg-slate-950 p-5 text-slate-100 sm:p-10"><div className="mx-auto max-w-7xl">
  <nav className="mb-8 flex flex-wrap gap-5 text-sm text-teal-300"><a href="/">Home & Maataa</a><a href="/helpers">Helpers & schedule</a><a href="/event-planners">Find businesses</a><a href="/event-planners/studio">Search designer</a></nav>
  <header className="mb-8"><p className="text-xs tracking-[.2em] text-teal-300">BRAHMINI ROADMAP</p><h1 className="mt-3 text-4xl font-semibold">See what is ready and what comes next.</h1><p className="mt-3 max-w-3xl text-slate-300">One live view of collection progress, Maataa conversations, helpers, scheduled work and delivery milestones. It refreshes every 10 seconds.</p></header>
  {error&&<p role="alert" className="my-5 rounded-xl border border-red-800 bg-red-950/40 p-4 text-red-200">{error}</p>}
  <section aria-label="Current progress" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
   <article className={card}><p className="text-sm text-slate-400">Districts checked</p><p className="mt-2 text-3xl">{collection?`${collection.completed} / ${collection.total}`:'Unavailable'}</p>{collection&&<><div className="mt-4 h-2 rounded bg-slate-700"><div className="h-2 rounded bg-teal-300" style={{width:`${collection.percent}%`}}/></div><p className="mt-2 text-sm">{collection.percent}% · {collection.pending} waiting</p></>}</article>
   <article className={card}><p className="text-sm text-slate-400">Businesses found</p><p className="mt-2 text-3xl">{collection?.businesses.toLocaleString()??'Unavailable'}</p><p className="mt-3 text-sm text-slate-400">Source-listed candidates; operating status is unverified.</p></article>
   <article className={card}><p className="text-sm text-slate-400">Saved conversations</p><p className="mt-2 text-3xl">{workspace?.conversations??'Unavailable'}</p><p className="mt-3 text-sm">{workspace?`${workspace.published} published updates · ${workspace.drafts} drafts`:'Local store unavailable'}</p></article>
   <article className={card}><p className="text-sm text-slate-400">Helpers</p><p className="mt-2 text-3xl">{helpers?.total??'Unavailable'}</p><p className={`mt-3 text-sm ${helpers?.schedulerAvailable?'text-teal-300':'text-amber-300'}`}>{helpers?helpers.schedulerAvailable?'Scheduler available':`Scheduler offline · ${helpers.waiting} waiting`:'Local store unavailable'}</p></article>
  </section>
  <section className="mt-10"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-semibold">Delivery journey</h2><p className="mt-2 text-slate-400">A completion label means the named local feature and its recorded checks exist. It is not a production approval.</p></div><span className="text-xs text-slate-500">Updated {date(data?.generatedAt||null)}</span></div>
   <div className="grid gap-4 md:grid-cols-2">{data?.milestones.map((item,index)=><article className={card} key={item.id}><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-slate-500">Phase {index+1}</p><h3 className="mt-1 text-lg font-semibold">{item.title}</h3></div><span className={`rounded-full px-3 py-1 text-xs ${item.status==='complete'?'bg-emerald-950 text-emerald-200':item.status==='in_progress'?'bg-amber-950 text-amber-200':'bg-slate-800 text-slate-300'}`}>{statusLabel[item.status]}</span></div><p className="mt-4 text-xs text-slate-400">{item.commit?`Commit ${item.commit} · ${item.date}`:'No completion commit recorded'}</p><div className="mt-4 flex gap-4 text-sm text-teal-300">{item.href&&<a href={item.href}>Open feature →</a>}{item.evidence&&<a href={item.evidence}>Read evidence →</a>}</div></article>)}</div>
  </section>
  <section className="mt-10 grid gap-6 lg:grid-cols-3">
   <article className={card}><h2 className="text-xl font-semibold">Collection now</h2>{collection?<div className="mt-4 space-y-2 text-sm"><p>{collection.active?`${collection.active} district search running`:'No district search is running'}</p><p>{collection.pending} district searches remain</p><p>Status: {collection.runnerState}</p>{collection.pauseReason&&<p className="text-amber-200">Paused: {collection.pauseReason}</p>}<p className="text-slate-400">Last progress: {date(collection.lastProgressAt)}</p><a className="inline-block pt-2 text-teal-300" href="/event-planners">Open collection →</a></div>:<p className="mt-4 text-slate-400">Collection database unavailable.</p>}</article>
   <article className={card}><h2 className="text-xl font-semibold">Recent conversations</h2>{workspace?.recentConversations.length?<div className="mt-3 space-y-3">{workspace.recentConversations.map(item=><a className="block border-t border-slate-700 pt-3" key={item.id} href={`/?conversation=${item.id}#maataa-conversation`}><strong>{item.title}</strong><small className="mt-1 block text-slate-400">{item.category} · {date(item.updated_at)}</small></a>)}</div>:<p className="mt-4 text-slate-400">No saved conversations yet.</p>}</article>
   <article className={card}><h2 className="text-xl font-semibold">Helper work</h2>{helpers?.recentRuns.length?<div className="mt-3 space-y-3">{helpers.recentRuns.map(item=><div className="border-t border-slate-700 pt-3" key={item.id}><div className="flex justify-between gap-3"><strong>{item.name}</strong><span className="text-sm">{runLabel[item.status]||item.status}</span></div><small className="mt-1 block text-slate-400">{date(item.created_at)}</small>{item.error&&<p className="mt-2 text-sm text-amber-200">{item.error}</p>}{item.conversation_id&&<a className="mt-2 inline-block text-sm text-teal-300" href={`/?conversation=${item.conversation_id}#maataa-conversation`}>Read result →</a>}</div>)}</div>:<p className="mt-4 text-slate-400">No helper runs yet.</p>}<a className="mt-4 inline-block text-teal-300" href="/helpers">Open helpers →</a></article>
  </section>
  <section className={card+' mt-10'}><h2 className="text-xl font-semibold">Next release gates</h2><ol className="mt-4 grid gap-3 text-slate-300 md:grid-cols-2"><li>1. Finish and review the remaining district searches.</li><li>2. Add backup and restore for local databases.</li><li>3. Package the app and scheduler together.</li><li>4. Add authentication before network exposure.</li></ol></section>
 </div></main>;
}
