const { test, expect } = require('@playwright/test');
const http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {openDb,Store}=require('../lib/db'); const {BrowserService}=require('../lib/browser-service');
let server,base,dir,store,browser;
function fixture(req,res){const url=new URL(req.url,'http://x');if(url.pathname==='/file'){res.setHeader('Content-Disposition','attachment; filename=x.txt');return res.end('download');}if(url.pathname==='/upload'){let b=[];req.on('data',x=>b.push(x));return req.on('end',()=>res.end(`<body>upload:${crypto.createHash('sha256').update(Buffer.concat(b)).digest('hex')}</body>`));}const cookie=req.headers.cookie||'';res.setHeader('content-type','text/html');res.end(`<body>${url.pathname}<span id="cookie">${cookie}</span><a id="outside" href="http://example.com/">out</a><a id="nav" href="/next">next</a><a id="download" href="/file" download>download</a><form method="post" enctype="multipart/form-data" action="/upload"><input id="file" type="file"><button id="submit">submit</button></form><input id="text"><input id="password" type="password"></body>`);}
test.beforeAll(async()=>{server=http.createServer(fixture);await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;});
test.afterAll(async()=>new Promise(r=>server.close(r)));
test.beforeEach(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'nova-browser-'));const {db}=openDb(dir);store=new Store(db);store.allowEgress('127.0.0.1','test');browser=new BrowserService(store,dir);});
test.afterEach(async()=>{await browser.shutdown();fs.rmSync(dir,{recursive:true,force:true});});
async function open(agent='a',policy={}){return browser.open(`${base}/`,{agentId:agent,policy:{id:'test',...policy}});}
test('1 opens an allowed local page and persists evidence',async()=>{const p=await open();expect(p.ok).toBeTruthy();expect(store.browserPages('a')[0].sha256).toMatch(/^[a-f0-9]{64}$/);});
test('2 denies unallowlisted egress and records it',async()=>{await expect(browser.open('http://example.com/',{agentId:'a',policy:{id:'deny'}})).rejects.toThrow('Egress denied');expect(store.db.prepare('select allowed from browser_egress where domain=?').get('example.com').allowed).toBe(0);});
test('3 allows explicitly granted domain',async()=>{const p=await browser.open(`${base}/`,{agentId:'a',policy:{id:'grant',grants:['127.0.0.1']}});expect(p.pageId).toBeTruthy();});
test('4 reads visible page text',async()=>{const p=await open();expect((await browser.read(p.pageId)).text).toContain('/');});
test('5 clicks a local navigation',async()=>{const p=await open();expect((await browser.click(p.pageId,'#nav')).url).toContain('/next');});
test('6 types non-secret input',async()=>{const p=await open();expect((await browser.type(p.pageId,'#text','hello')).ok).toBeTruthy();});
test('7 rejects password input without secret grant',async()=>{const p=await open();await expect(browser.type(p.pageId,'#password','no')).rejects.toThrow('Credential entry');});
test('8 profiles are isolated',async()=>{const a=await browser.open(`${base}/`,{agentId:'one',policy:{id:'p'}});const b=await browser.open(`${base}/`,{agentId:'two',policy:{id:'p'}});expect(a.pageId).not.toBe(b.pageId);expect(store.browserPages('one')).toHaveLength(1);expect(store.browserPages('two')).toHaveLength(1);});
test('9 screenshot has a content hash',async()=>{const p=await open();const shot=await browser.screenshot(p.pageId);expect(fs.existsSync(shot.path)).toBeTruthy();expect(shot.sha256).toHaveLength(64);});
test('10 download requires approval and writes requested file',async()=>{const p=await open(),out=path.join(dir,'download.txt');await expect(browser.download(p.pageId,{selector:'#download',path:out})).rejects.toThrow('explicit approval');await browser.download(p.pageId,{selector:'#download',path:out,approve:true});expect(fs.readFileSync(out,'utf8')).toBe('download');});
test('11 upload requires approval',async()=>{const p=await open(),input=path.join(dir,'input.txt');fs.writeFileSync(input,'upload');await expect(browser.upload(p.pageId,{selector:'#file',path:input})).rejects.toThrow('explicit approval');expect((await browser.upload(p.pageId,{selector:'#file',path:input,approve:true,submitSelector:'#submit'})).ok).toBeTruthy();});
test('12 global halt prevents partial screenshots',async()=>{const p=await open();store.setGlobalHalt('1');await expect(browser.screenshot(p.pageId)).rejects.toThrow('kill switch');expect(store.browserPages('a')[0].sha256).toBeTruthy();});
