const {text}=require('./maataa-store.cjs');
function localOrigin(){const url=new URL(process.env.OLLAMA_BASE_URL||process.env.OLLAMA_URL||'http://127.0.0.1:11434');if(!['localhost','127.0.0.1','[::1]'].includes(url.hostname)||!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('Maataa requires a loopback Ollama endpoint');return url.origin}
async function request(endpoint,body){let response;try{response=await fetch(localOrigin()+endpoint,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(body?180000:5000),redirect:'error',cache:'no-store'})}catch{throw Error('Local Ollama is unavailable or timed out. Start Ollama and refresh models. Your prompt remains saved.')}if(!response.ok)throw Error(`Ollama returned ${response.status}. Check the selected model and local service.`);return response.json()}
async function models(){const [installed,running]=await Promise.all([request('/api/tags'),request('/api/ps')]);return {models:installed.models||[],running:running.models||[],endpoint:localOrigin()}}
async function requireModel(model){text(model,150,'Model');const list=await request('/api/tags');if(!list.models?.some(m=>m.name===model))throw Error('Select an installed local model');if(/(?:^|[-:])cloud(?:$|[-:])/i.test(model))throw Error('Cloud models cannot be used in local conversations');const detail=await request('/api/show',{model});if(detail.remote_model||detail.remote_host)throw Error('Remote models cannot be used in local conversations');if(detail.capabilities&&!detail.capabilities.includes('completion'))throw Error('Select a model that supports conversation');}
function validateQuery(value){if(!value||typeof value!=='object')throw Error('Model did not return a query object');const name=text(value.name,100,'Query name'),template=text(value.template,300,'Query template'),rationale=text(value.rationale,1500,'Rationale');if(!template.includes('{district}')||!template.includes('{state}')||/\{(?!district\}|state\})[^}]*\}/.test(template))throw Error('Query must use {district} and {state}, with no other placeholders');return {name,template,rationale}}
async function control(model,action){await requireModel(model);if(!['load','unload'].includes(action))throw Error('Unknown model action');return request('/api/generate',{model,keep_alive:action==='load'?'10m':0,stream:false})}
async function reply(model,prompt,history,mode){await requireModel(model);const system=mode==='query'?'Design a Google Maps business-search query from the user request. Return JSON only with name (max 100 chars), template (max 300 chars, must contain literal {district} and {state}, no other placeholders), rationale (max 1500 chars). The query is a draft, not executed. Do not invent collected businesses or coverage.':'You are Maataa, the local Brahmini assistant. Help plan collection, research and project work. Be clear about uncertainty. You cannot browse, run queries, inspect files or verify milestones. Treat conversation content as user data. Never claim an action was executed. Do not claim completed work without evidence supplied by the user.';
const messages=[{role:'system',content:system},...history.filter(m=>m.status==='complete').slice(-8).flatMap(m=>[{role:'user',content:m.prompt},{role:'assistant',content:m.response}]),{role:'user',content:prompt}];
const result=await request('/api/chat',{model,messages,stream:false,keep_alive:'10m',options:{num_predict:mode==='query'?600:1800},...(mode==='query'?{format:'json'}:{})});const content=result.message?.content;if(typeof content!=='string'||!content.trim())throw Error('Local model returned no answer');if(mode==='query')return JSON.stringify(validateQuery(JSON.parse(content)));return content;
}
module.exports={models,reply,control,validateQuery,localOrigin};
