const sqlite3=require('sqlite3');const fs=require('node:fs');const path=require('node:path');const {randomUUID}=require('node:crypto');const {text}=require('./maataa-store.cjs');
const run=(d,s,a=[])=>new Promise((r,j)=>d.run(s,a,function(e){e?j(e):r(this.changes)}));const all=(d,s,a=[])=>new Promise((r,j)=>d.all(s,a,(e,v)=>e?j(e):r(v)));
function createHelpers(file=process.env.MAATAA_HELPERS_DB||path.join(process.cwd(),'data/maataa/helpers.db')){
async function use(fn){fs.mkdirSync(path.dirname(file),{recursive:true});const d=await new Promise((r,j)=>{const db=new sqlite3.Database(file,e=>e?j(e):r(db))});try{await run(d,'PRAGMA busy_timeout=5000');await run(d,'CREATE TABLE IF NOT EXISTS helpers(id TEXT PRIMARY KEY,name TEXT,prompt TEXT,model TEXT,mode TEXT,category TEXT,interval_minutes INTEGER,next_run TEXT,enabled INTEGER,created_at TEXT)');await run(d,'CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY,helper_id TEXT,name TEXT,prompt TEXT,model TEXT,mode TEXT,category TEXT,status TEXT,created_at TEXT,started_at TEXT,finished_at TEXT,conversation_id TEXT,error TEXT)');await run(d,'CREATE TABLE IF NOT EXISTS worker(id INTEGER PRIMARY KEY,heartbeat TEXT)');return await fn(d)}finally{await new Promise((r,j)=>d.close(e=>e?j(e):r()))}}
return {
 snapshot:()=>use(async d=>({helpers:await all(d,'SELECT * FROM helpers ORDER BY created_at DESC'),runs:await all(d,'SELECT * FROM runs ORDER BY created_at DESC LIMIT 100'),worker:(await all(d,'SELECT * FROM worker WHERE id=1'))[0]||null})),
 create:b=>use(async d=>{if(!['chat','query'].includes(b.mode))throw Error('Choose a helper type');const interval=Number(b.interval_minutes);if(![0,60,360,1440,10080].includes(interval))throw Error('Choose a supported schedule');let next=null;if(interval){const time=Date.parse(b.next_run);if(!Number.isFinite(time)||time<Date.now()+30000)throw Error('Choose a start time at least one minute from now');next=new Date(time).toISOString()}const id=randomUUID();await run(d,'INSERT INTO helpers VALUES(?,?,?,?,?,?,?,?,?,?)',[id,text(b.name,100,'Name'),text(b.prompt,8000,'Instructions'),text(b.model,150,'Model'),b.mode,text(b.category,60,'Category'),interval,next,interval?1:0,new Date().toISOString()]);return {id}}),
 toggle:b=>use(async d=>{const [h]=await all(d,'SELECT * FROM helpers WHERE id=?',[b.id]);if(!h)throw Error('Helper not found');if(b.enabled&&!h.interval_minutes)throw Error('This helper is run manually');await run(d,'UPDATE helpers SET enabled=?,next_run=? WHERE id=?',[b.enabled?1:0,b.enabled?new Date(Date.now()+h.interval_minutes*60000).toISOString():h.next_run,b.id]);return {ok:true}}),
 queue:id=>use(async d=>{await run(d,'BEGIN IMMEDIATE');try{const [h]=await all(d,'SELECT * FROM helpers WHERE id=?',[id]);if(!h)throw Error('Helper not found');if((await all(d,"SELECT id FROM runs WHERE helper_id=? AND status IN ('queued','running')",[id])).length)throw Error('This helper already has a queued or running task');const rid=randomUUID();await run(d,'INSERT INTO runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[rid,h.id,h.name,h.prompt,h.model,h.mode,h.category,'queued',new Date().toISOString(),null,null,null,null]);await run(d,'COMMIT');return {id:rid}}catch(e){await run(d,'ROLLBACK');throw e}}),
 cancel:id=>use(async d=>{if(!await run(d,"UPDATE runs SET status='cancelled',finished_at=? WHERE id=? AND status='queued'",[new Date().toISOString(),id]))throw Error('Only waiting tasks can be cancelled');return {ok:true}}),
 tick:()=>use(async d=>{await run(d,'BEGIN IMMEDIATE');try{const now=new Date().toISOString();await run(d,'INSERT OR REPLACE INTO worker VALUES(1,?)',[now]);await run(d,"UPDATE runs SET status='failed',error='Worker interrupted. Review the conversation before running again.',finished_at=? WHERE status='running' AND started_at<?",[now,new Date(Date.now()-300000).toISOString()]);for(const h of await all(d,'SELECT * FROM helpers WHERE enabled=1 AND next_run<=?',[now])){if(!(await all(d,"SELECT id FROM runs WHERE helper_id=? AND status IN ('queued','running')",[h.id])).length)await run(d,'INSERT INTO runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[randomUUID(),h.id,h.name,h.prompt,h.model,h.mode,h.category,'queued',now,null,null,null,null]);await run(d,'UPDATE helpers SET next_run=? WHERE id=?',[new Date(Date.now()+h.interval_minutes*60000).toISOString(),h.id])}let task=null;if(!(await all(d,"SELECT id FROM runs WHERE status='running'")).length){[task]=await all(d,"SELECT * FROM runs WHERE status='queued' ORDER BY created_at LIMIT 1");if(task)await run(d,"UPDATE runs SET status='running',started_at=? WHERE id=?",[now,task.id])}await run(d,'COMMIT');return task||null}catch(e){await run(d,'ROLLBACK');throw e}}),
 attach:(id,cid)=>use(d=>run(d,'UPDATE runs SET conversation_id=? WHERE id=?',[cid,id])),
 finish:(id,error)=>use(async d=>{await run(d,"UPDATE runs SET status=?,error=?,finished_at=? WHERE id=? AND status='running'",[error?'failed':'complete',error||null,new Date().toISOString(),id]);if(error){await run(d,'UPDATE helpers SET enabled=0 WHERE id=(SELECT helper_id FROM runs WHERE id=?)',[id])}}),
 }
}
module.exports={createHelpers};
