'use client';
import {useEffect,useState} from 'react';
type Method={id:string;name:string;template:string;created_at:string};
type Task={id:string;district:string;state:string;query:string;outcome:string;status:string;results:number;started_at:string;finished_at:string;note:string};
type History={id:string;query:string;status:string;started_at:string;finished_at:string;results:number;note:string};
export default function Studio(){
 const [live,setLive]=useState<{matchedPlanners:number;runnerState:string;counts:{status:string;count:number}[];totalDistricts:number}|null>(null),[updated,setUpdated]=useState(''),[liveError,setLiveError]=useState('');
 useEffect(()=>{let active=true;async function poll(){try{const r=await fetch('/api/event-planners?mode=summary',{cache:'no-store'});if(!r.ok)throw Error('Live counters unavailable');const value=await r.json();if(active){setLive(value);setUpdated(new Date().toLocaleTimeString());setLiveError('');}}catch{if(active)setLiveError('Updates interrupted — showing last received counts');}}void poll();const timer=setInterval(poll,5000);return()=>{active=false;clearInterval(timer);};},[]);
 const count=(...statuses:string[])=>live?live.counts.filter(c=>statuses.includes(c.status)).reduce((n,c)=>n+c.count,0):null;
 const counters=[['Total districts',live?.totalDistricts],['Succeeded · limited',count('limited_view','visible_list_exhausted','no_results')],['Pending',count('pending')],['Running',count('running')],['Failed / blocked',count('failed','blocked')],['Partial',count('partial')],['Planner matches',live?.matchedPlanners]];
 const [data,setData]=useState<{methods:Method[];tasks:Task[];history:History[]}>({methods:[],tasks:[],history:[]});
 const [name,setName]=useState('District planner search'),[template,setTemplate]=useState('event planners in {district} district, {state}, India'),[method,setMethod]=useState('original'),[district,setDistrict]=useState(''),[filter,setFilter]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function refresh(){const r=await fetch('/api/event-planners/studio');if(!r.ok)throw Error('Cannot load query history');setData(await r.json());}
 useEffect(()=>{void refresh().catch(e=>setMessage(e.message));const timer=setInterval(()=>void refresh().catch(e=>setMessage(e.message)),10000);return()=>clearInterval(timer);},[]);
 async function send(action:string){setBusy(true);setMessage('');try{const r=await fetch('/api/event-planners/studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,name,template,methodId:method,districtId:district})});const b=await r.json();if(!r.ok)throw Error(b.error);if(action==='save'){setMethod(b.id);setMessage('Saved immutable method version with timestamp.');}else setMessage(`Test ${b.status}: ${b.results} candidates. Results saved in history.`);await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 const selected=data.tasks.find(t=>t.id===district),chosen=data.methods.find(m=>m.id===method);
 return <main className="min-h-screen bg-slate-950 text-slate-100 p-8"><div className="max-w-6xl mx-auto space-y-6"><a className="text-teal-300" href="/event-planners">← Collected planners</a><h1 className="text-3xl">Query designer and run history</h1><p>Successful searches are retained and skipped on retry. Source-limited success means the search returned normally, not exhaustive district coverage. Tests retain separate results and do not change district collection status.</p>
 <section aria-label="Live collection counters"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{counters.map(([label,value])=><div key={String(label)} className="rounded-xl border border-slate-700 bg-slate-900 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums text-teal-300">{value==null?'—':Number(value).toLocaleString()}</p></div>)}</div><p className="mt-3 text-sm text-slate-400" role="status">Runner: {live?.runnerState||'Loading…'} · Refreshes every 5 seconds{updated?` · Updated ${updated}`:''}{liveError?` · ${liveError}`:''}</p></section>
 <section className="grid gap-3 rounded border border-slate-700 p-5"><h2 className="text-xl">Design a method</h2><label>Name<input className="block w-full bg-slate-800 p-2" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label>Template<textarea className="block w-full bg-slate-800 p-2" value={template} onChange={e=>setTemplate(e.target.value)} maxLength={300}/></label><p>Required placeholders: {'{district}'} and {'{state}'}. Each save creates a new version.</p><button disabled={busy} className="bg-teal-700 p-2" onClick={()=>void send('save')}>Save method version</button></section>
 <section className="grid gap-3 rounded border border-slate-700 p-5"><h2 className="text-xl">Test a saved method</h2><select aria-label="Saved method" className="bg-slate-800 p-2" value={method} onChange={e=>setMethod(e.target.value)}>{data.methods.map(m=><option key={m.id} value={m.id}>{m.name} · {m.created_at}</option>)}</select><select aria-label="Test district" className="bg-slate-800 p-2" value={district} onChange={e=>setDistrict(e.target.value)}><option value="">Choose district</option>{data.tasks.map(t=><option key={t.id} value={t.id}>{t.state} / {t.district}</option>)}</select><p>{selected&&chosen?chosen.template.replaceAll('{district}',selected.district).replaceAll('{state}',selected.state):'Choose a district to preview the saved query.'}</p><button disabled={busy||!district} className="bg-teal-700 p-2 disabled:opacity-40" onClick={()=>void send('test')}>{busy?'Working…':'Run Google Maps test'}</button><p role="status">{message}</p></section>
 <section><h2 className="text-xl">District queries ({data.tasks.length})</h2><select aria-label="Status filter" className="bg-slate-800 p-2 my-3" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{['Succeeded (source-limited)','Failed','Partial','pending','running'].map(s=><option key={s}>{s}</option>)}</select><div className="max-h-[500px] overflow-auto"><table className="w-full text-sm"><thead><tr>{['Query','Outcome','Candidates','Started / finished'].map(h=><th className="text-left p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data.tasks.filter(t=>!filter||t.outcome===filter).map(t=><tr key={t.id} className="border-t border-slate-700"><td className="p-2">{t.query}</td><td className="p-2" title={t.note}>{t.outcome}</td><td>{t.results}</td><td>{t.started_at||'—'}<br/>{t.finished_at||'—'}</td></tr>)}</tbody></table></div></section>
 <section><h2 className="text-xl">Recent attempts and tests</h2>{data.history.map(h=><article key={h.id} className="border-t border-slate-700 py-3 text-sm"><p>{h.query} · {h.status} · {h.results} candidates</p><p>{h.started_at} → {h.finished_at||'Running'}</p><p className="text-slate-400">{h.note}</p></article>)}</section></div></main>;
}
