'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const evidence=require('../lib/collector-evidence');
function memoryStore(){const stores=new Map();return{all(name){return[...(stores.get(name)?.values()||[])];},get(name,id){return stores.get(name)?.get(id)||null;},put(name,row){if(!stores.has(name))stores.set(name,new Map());stores.get(name).set(row.id,row);return row;}};}
function raw(name='Venue A'){return{name,maps_url:'https://www.google.com/maps/place/venue-a',source:'Google Maps public search',verification_status:'SOURCE_LISTED_UNVERIFIED',district_membership:'UNVERIFIED_SEARCH_ASSOCIATION'};}
function envelope(overrides={}){return{schemaVersion:1,queryHistoryId:'query-1',taskId:'DL:1',methodId:'venue-banquet-halls',query:'banquet halls in New Delhi district, Delhi, India',district:'New Delhi',category:'banquet halls',sourceUrl:'https://www.google.com/maps/search/banquet%20halls?hl=en',startedAt:'2026-09-15T00:00:00.000Z',finishedAt:'2026-09-15T00:00:03.000Z',status:'limited_view',resultCount:1,limitation:'Google limited-view banner present',rawRecords:[raw()],...overrides};}
const run={id:'run-1',categories:['banquet halls']};

test('versioned collector evidence preserves source timestamps and every raw observation',()=>{const store=memoryStore();const saved=evidence.persist(store,run,envelope());assert.equal(saved.startedAt,'2026-09-15T00:00:00.000Z');assert.equal(saved.finishedAt,'2026-09-15T00:00:03.000Z');assert.equal(saved.rawRecords.length,1);const observations=store.all('venueObservations');assert.equal(observations.length,1);assert.equal(observations[0].queryHistoryId,'query-1');assert.deepEqual(observations[0].raw,raw());});
test('replayed query evidence is idempotent while observations remain query-specific',()=>{const store=memoryStore();evidence.persist(store,run,envelope());evidence.persist(store,run,envelope());assert.equal(store.all('collectorEvidence').length,1);assert.equal(store.all('venueObservations').length,1);evidence.persist(store,run,envelope({queryHistoryId:'query-2'}));assert.equal(store.all('venueObservations').length,2);assert.equal(new Set(store.all('venueObservations').map(x=>x.listingKey)).size,1);});
test('collector evidence rejects malformed schema, source, timestamps, count and provenance',()=>{for(const bad of [envelope({schemaVersion:0}),envelope({sourceUrl:'https://example.com'}),envelope({finishedAt:'2025-01-01T00:00:00Z'}),envelope({resultCount:2}),envelope({rawRecords:[raw(),{...raw('B'),source:'unknown'}]})])assert.throws(()=>evidence.normalize(run,bad));});
